#!/usr/bin/env python3
"""Generates src/runways_table.inc from the OurAirports dataset.

The runways of every airport in src/airports.cpp's table, for the airport
zoom: each one's two ends, as the numbers painted on them and where they are,
with its width, the airport's elevation, and whether it is closed - a closed
runway is still there on the ground, and the zoom draws it as one.
OurAirports (ourairports.com) is public domain, and the same source the
airport table came from.

    tools/gen_runways.py                         # downloads the two CSVs
    tools/gen_runways.py airports.csv runways.csv

Left out: helipads, water runways, and the few without both ends placed -
there is nothing to draw those by.
"""

import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_URL = "https://davidmegginson.github.io/ourairports-data/"
DEFAULT_WIDTH_FT = 150  # a typical airliner runway, for the rows that don't say


def open_csv(arg, name):
    if arg:
        return open(arg, encoding="utf-8", newline="")
    with urllib.request.urlopen(DATA_URL + name) as r:
        return io.StringIO(r.read().decode("utf-8"), newline="")


def main():
    args = sys.argv[1:] + [None, None]
    codes = re.findall(r'\{"([A-Z]{3})",', (ROOT / "src" / "airports.cpp").read_text())

    # The same filter the airport table was made with, so each code is the
    # one airport it names there.
    idents = {}
    elevation = {}
    with open_csv(args[0], "airports.csv") as f:
        for r in csv.DictReader(f):
            if (r["iata_code"] in codes and r["type"] in ("large_airport", "medium_airport")
                    and r["scheduled_service"] == "yes"):
                idents[r["ident"]] = r["iata_code"]
                elevation[r["iata_code"]] = int(float(r["elevation_ft"] or 0))

    rows = []
    with open_csv(args[1], "runways.csv") as f:
        for r in csv.DictReader(f):
            code = idents.get(r["airport_ident"])
            if code is None:
                continue
            le, he = r["le_ident"].strip(), r["he_ident"].strip()
            # A runway number starts with a digit. That leaves out helipads
            # (H1), unlabelled rows, and water runways (18W) with the rest.
            if not (le[:1].isdigit() and he[:1].isdigit()) or le.endswith("W") or len(le) > 3 or len(he) > 3:
                continue
            ends = [r["le_latitude_deg"], r["le_longitude_deg"], r["he_latitude_deg"], r["he_longitude_deg"]]
            if not all(ends):
                continue
            width = int(float(r["width_ft"])) if r["width_ft"] else DEFAULT_WIDTH_FT
            lat1, lon1, lat2, lon2 = (float(v) for v in ends)
            closed = "true" if r["closed"] == "1" else "false"
            rows.append((code, width, elevation[code], closed, le, lat1, lon1, he, lat2, lon2))

    rows.sort(key=lambda row: row[0])  # stable: an airport's runways keep the dataset's order
    out = ROOT / "src" / "runways_table.inc"
    with open(out, "w") as f:
        f.write("// Generated by tools/gen_runways.py from the public-domain OurAirports\n")
        f.write("// dataset (ourairports.com) - regenerate rather than edit.\n")
        f.write("// {airport, width ft, elevation ft, closed, {{end, lat, lon}, {end, lat, lon}}}\n")
        for code, width, elev, closed, le, lat1, lon1, he, lat2, lon2 in rows:
            f.write(f'{{"{code}", {width}, {elev}, {closed}, {{{{"{le}", {lat1:.6f}f, {lon1:.6f}f}}, '
                    f'{{"{he}", {lat2:.6f}f, {lon2:.6f}f}}}}}},\n')
    airports = len({row[0] for row in rows})
    closed = sum(1 for row in rows if row[3] == "true")
    print(f"{len(rows)} runways ({closed} closed) at {airports} of {len(codes)} airports -> {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
