"""Synthesise the splash screen's jet take-off into src/jet_table.inc.

    python tools/gen_jet.py [--wav jet.wav]

No recording and nothing to install: the sound is made from noise and a
sine, as a sound designer would rough one out. The engines spool up - a
broadband roar opening out as the thrust comes on, the turbines' whine rising
over it - hold at take-off power with the crackle of the exhaust, and then
the aircraft climbs away, the roar closing down and the whine dropping a few
per cent as it goes. The Tab5's speaker has nothing much below 300Hz, so the
weight is in the roar's mid-range rather than a rumble it couldn't play.

Mono 16-bit at 16kHz, about 3.6 seconds and 115KB of flash; --wav writes it
out too, to listen to.
"""
import argparse
import math
import random
import struct
import wave

RATE = 16000
SECONDS = 3.6
SPOOL_S, HOLD_S = 2.0, 2.7  # engines up by SPOOL_S; climbing away after HOLD_S


def smoothstep(x):
    x = min(max(x, 0.0), 1.0)
    return x * x * (3 - 2 * x)


def synth():
    rnd = random.Random(737)
    n = int(RATE * SECONDS)
    out = []
    # A two-pole state-variable low-pass for the roar, and a one-pole for
    # the crackle's pops; their states carry from sample to sample.
    low = band = 0.0
    pop = 0.0
    phase = phase2 = 0.0
    for i in range(n):
        t = i / RATE
        spool = smoothstep(t / SPOOL_S)
        away = smoothstep((t - HOLD_S) / (SECONDS - HOLD_S))
        # Loudness: in from near nothing, held, then away and gone.
        amp = (0.08 + 0.92 * spool) * (1.0 - 0.95 * away)

        # The roar: noise through a low-pass that opens with the thrust and
        # closes again as it climbs away, with a little resonance.
        fc = 350 + 2600 * spool - 1900 * away
        f = 2 * math.sin(math.pi * fc / RATE)
        q = 0.55
        noise = rnd.uniform(-1, 1)
        high = noise - low - q * band
        band += f * high
        low += f * band
        roar = low * 0.9 + band * 0.35

        # The turbines: a whine climbing with the spool, wavering a little,
        # dropping as the aircraft draws away.
        hz = (1400 + 2600 * spool) * (1.0 - 0.06 * away) * (1 + 0.004 * math.sin(2 * math.pi * 5.3 * t))
        phase += 2 * math.pi * hz / RATE
        phase2 += 2 * math.pi * hz * 1.52 / RATE
        whine = (math.sin(phase) * 0.10 + math.sin(phase2) * 0.04) * spool * (1.0 - 0.7 * away)

        # The crackle of the exhaust at full power: sparse pops, softened.
        if rnd.random() < 0.0045 * spool * (1.0 - away):
            pop += rnd.uniform(-1, 1) * 2.5
        pop *= 0.82
        out.append(amp * (roar + pop * 0.5) + whine)

    peak = max(abs(s) for s in out)
    # Squeezed as the voice is, so it is as loud on the small speaker.
    drive = 2.2
    return [math.tanh(drive * s / peak) / math.tanh(drive) * 0.92 for s in out]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="src/jet_table.inc")
    ap.add_argument("--wav")
    args = ap.parse_args()
    samples = [int(round(s * 32767)) for s in synth()]
    with open(args.out, "w") as f:
        f.write("// Generated by tools/gen_jet.py - do not edit.\n")
        f.write("// The splash screen's jet take-off, as 16-bit mono samples.\n")
        f.write(f"constexpr uint32_t JET_RATE = {RATE};\n")
        f.write(f"const int16_t JET_TAKEOFF[] = {{  // {len(samples) / RATE:.2f}s\n")
        for i in range(0, len(samples), 16):
            f.write("    " + ", ".join(str(s) for s in samples[i:i + 16]) + ",\n")
        f.write("};\n")
    if args.wav:
        with wave.open(args.wav, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(RATE)
            w.writeframes(struct.pack(f"<{len(samples)}h", *samples))
    print(f"{args.out}: {len(samples)} samples, {len(samples) / RATE:.2f}s, {len(samples) * 2 // 1024}KB")


if __name__ == "__main__":
    main()
