#!/usr/bin/env python3
"""Generates src/navaids_table.inc from the OurAirports dataset.

The radio beacons aircraft navigate by that a radar watcher reads off a
chart: VORs, DMEs and TACANs, alone or co-located - the VOR-DMEs, VORTACs
and NDB-DMEs. Each with its ident, name, frequency, DME channel and where it
is, for the radar to mark. OurAirports (ourairports.com) is public domain,
and the same source the airport and runway tables came from.

    tools/gen_navaids.py               # downloads navaids.csv
    tools/gen_navaids.py navaids.csv

Left out: plain NDBs - twice as many again, and clutter round every airfield -
any row without a position, and the few marked closed or decommissioned, or
given a frequency of -1 for it.
"""

import csv
import io
import sys
import unicodedata
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_URL = "https://davidmegginson.github.io/ourairports-data/"
TYPES = {
    "VOR": "VOR",
    "VOR-DME": "VOR_DME",
    "VORTAC": "VORTAC",
    "TACAN": "TACAN",
    "DME": "DME",
    "NDB-DME": "NDB_DME",
}
NAME_MAX = 31


def open_csv(arg, name):
    if arg:
        return open(arg, encoding="utf-8", newline="")
    with urllib.request.urlopen(DATA_URL + name) as r:
        return io.StringIO(r.read().decode("utf-8"), newline="")


# The display's font is plain ASCII: accents dropped rather than drawn as junk.
def ascii_text(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    return s.replace("\\", "/").replace('"', "'").strip()


def main():
    args = sys.argv[1:] + [None]
    rows = []
    with open_csv(args[0], "navaids.csv") as f:
        for r in csv.DictReader(f):
            kind = TYPES.get(r["type"])
            if kind is None or not r["latitude_deg"] or not r["longitude_deg"]:
                continue
            name = r["name"].lower()
            if "closed" in name or "decommission" in name or float(r["frequency_khz"] or 0) < 0:
                continue
            ident = ascii_text(r["ident"])[:4]
            if not ident:
                continue
            rows.append((
                float(r["latitude_deg"]),
                ident,
                kind,
                ascii_text(r["dme_channel"])[:4],
                int(float(r["frequency_khz"] or 0)),
                float(r["longitude_deg"]),
                ascii_text(r["name"])[:NAME_MAX],
                ascii_text(r["associated_airport"])[:4],
            ))
    # By latitude, so the radar's lookup can skip straight to its band.
    rows.sort()

    out = [
        "// Generated by tools/gen_navaids.py from OurAirports' navaids.csv - do not edit.",
        "// ident, type, DME channel, frequency (kHz), lat, lon, name, airport - by latitude.",
    ]
    for lat, ident, kind, channel, freq, lon, name, airport in rows:
        out.append(f'{{"{ident}", NavaidType::{kind}, "{channel}", {freq}, {lat:.6f}f, {lon:.6f}f, '
                   f'"{name}", "{airport}"}},')
    (ROOT / "src" / "navaids_table.inc").write_text("\n".join(out) + "\n")
    print(f"{len(rows)} navaids")


if __name__ == "__main__":
    main()
