#include "navaids.h"

#include <math.h>

#include <algorithm>

namespace {

// Every VOR, DME and TACAN, from the public-domain OurAirports dataset -
// generated by tools/gen_navaids.py. By latitude. About 200KB of flash.
const Navaid NAVAIDS[] = {
#include "navaids_table.inc"
};
constexpr size_t NAVAID_COUNT = sizeof(NAVAIDS) / sizeof(NAVAIDS[0]);

// The last lookup: the radar asks for the same one every refresh, and the
// centre only moves on following, a poll at a time.
struct WithinCache {
    double lat = NAN, lon = NAN;
    float rangeNm = -1;
    std::vector<const Navaid *> navaids;
};
WithinCache g_within;

}  // namespace

const std::vector<const Navaid *> &navaidsWithin(double lat, double lon, float rangeNm) {
    WithinCache &c = g_within;
    if (c.lat == lat && c.lon == lon && c.rangeNm == rangeNm) {
        return c.navaids;
    }
    // The same flat-earth distance the radar projects with, so everything
    // returned lands inside its outer ring - from the band of latitude it
    // could be in, which the table's order lets a search go straight to.
    float flat = (float)lat, flon = (float)lon;
    float cosLat = cosf(flat * (float)M_PI / 180.0f);
    float max2 = rangeNm * rangeNm;
    float south = flat - rangeNm / 60.0f, north = flat + rangeNm / 60.0f;
    const Navaid *first = std::lower_bound(NAVAIDS, NAVAIDS + NAVAID_COUNT, south,
                                           [](const Navaid &n, float l) { return n.lat < l; });
    std::vector<std::pair<float, const Navaid *>> found;
    for (const Navaid *n = first; n != NAVAIDS + NAVAID_COUNT && n->lat <= north; n++) {
        float dLon = n->lon - flon;
        if (dLon > 180.0f) dLon -= 360.0f;
        if (dLon < -180.0f) dLon += 360.0f;
        float dx = dLon * 60.0f * cosLat, dy = (n->lat - flat) * 60.0f;
        float d2 = dx * dx + dy * dy;
        if (d2 <= max2) {
            found.push_back({d2, n});
        }
    }
    std::sort(found.begin(), found.end(),
              [](const std::pair<float, const Navaid *> &a, const std::pair<float, const Navaid *> &b) {
                  return a.first < b.first;
              });
    c.navaids.clear();
    for (const auto &f : found) {
        c.navaids.push_back(f.second);
    }
    c.lat = lat;
    c.lon = lon;
    c.rangeNm = rangeNm;
    return c.navaids;
}

const char *navaidTypeName(NavaidType type) {
    switch (type) {
    case NavaidType::VOR:
        return "VOR";
    case NavaidType::VOR_DME:
        return "VOR-DME";
    case NavaidType::VORTAC:
        return "VORTAC";
    case NavaidType::TACAN:
        return "TACAN";
    case NavaidType::DME:
        return "DME";
    case NavaidType::NDB_DME:
        return "NDB-DME";
    }
    return "";
}

String navaidFrequency(const Navaid &n) {
    if (n.freqKhz == 0) {
        return String("");
    }
    if (n.type == NavaidType::NDB_DME) {
        return String(n.freqKhz);
    }
    char buf[12];
    snprintf(buf, sizeof(buf), "%.2f", n.freqKhz / 1000.0);
    return String(buf);
}

String navaidLabel(const Navaid &n) {
    String tuned = n.type == NavaidType::TACAN && n.channel[0] ? String(n.channel) : navaidFrequency(n);
    return tuned.length() ? String(n.ident) + " " + tuned : String(n.ident);
}
