#include "runways.h"

#include <string.h>

#include <algorithm>

namespace {

// Every runway at the airports in the airport table, sorted by airport, from
// the public-domain OurAirports dataset - generated by tools/gen_runways.py.
// About 155KB of flash.
const Runway RUNWAYS[] = {
#include "runways_table.inc"
};

}  // namespace

const Runway *runwaysAt(const String &code, int &count) {
    auto less = [](const Runway &r, const char *c) { return strcmp(r.code, c) < 0; };
    const Runway *end = RUNWAYS + sizeof(RUNWAYS) / sizeof(RUNWAYS[0]);
    const Runway *first = std::lower_bound(RUNWAYS, end, code.c_str(), less);
    const Runway *last = first;
    while (last != end && code == last->code) {
        last++;
    }
    count = (int)(last - first);
    return count ? first : nullptr;
}
